SELECT
    TO_CHAR(T1.DT_MES_COMPETENCIA, 'YYYY-MM') AS COMPETENCIA,
    T1.NR_SEQ_PLANO AS PRODUTO,
    T1.IE_REGULAMENTACAO AS REGULAMENTACAO,
    T1.IE_TIPO_CONTRATACAO AS TIPO_CONTRATACAO,
    T2.DS_PLANO AS NOME_PLANO,
    SUM(T1.VL_MENSALIDADE) AS MENSALIDADE,
    SUM(T1.VL_COPARTICIPACAO) AS COPARTICIPACAO,
    SUM(T1.VL_CONTA) AS CONTA,
    SUM(T1.VL_COMISSAO) AS COMISSAO,
    SUM(T1.VL_RESSARCIR) AS SUS,
    SUM(T1.VL_RECURSO) AS GLOSA,
    SUM(T1.VL_TAXA) AS TAXA,
    SUM(T1.VL_REEMBOLSO) AS REEMBOLSO,
    SUM(T1.VL_RECEITAS) AS RECEITAS,
    SUM(T1.VL_DESPESAS) AS DESPESAS,
    SUM(T1.VL_ASSIST) AS VL_ASSIST,
    --Verificar para quê serve
        --SUM(T1.VL_ANTECIPACAO), 
        --SUM(T1.VL_PRO_RATA),
        --SUM(T1.VL_FATURADO),
    COUNT(DISTINCT CASE WHEN IE_TIPO_SEGURADO IS NOT NULL THEN T1.NR_SEQ_SEGURADO ELSE NULL END) AS QTD_SEGURADOS, --Validado

    CASE 
        WHEN SUM(T1.VL_MENSALIDADE) IS NULL THEN NULL -- Se mensalidade for nula
        ELSE
            CAST(
                (
                    CASE WHEN SUM(T1.VL_CONTA) IS NOT NULL THEN SUM(T1.VL_CONTA) ELSE 0 END
                    + CASE WHEN SUM(T1.VL_RESSARCIR) IS NOT NULL THEN SUM(T1.VL_RESSARCIR) ELSE 0 END
                    + CASE WHEN SUM(T1.VL_REEMBOLSO) IS NOT NULL THEN SUM(T1.VL_REEMBOLSO) ELSE 0 END
                    + CASE WHEN SUM(T1.VL_RECURSO) IS NOT NULL THEN SUM(T1.VL_RECURSO) ELSE 0 END
                    - CASE WHEN SUM(T1.VL_COPARTICIPACAO) IS NOT NULL THEN SUM(T1.VL_COPARTICIPACAO) ELSE 0 END
                ) 
                / SUM(T1.VL_MENSALIDADE) AS DECIMAL(10, 5)) END AS SINSITRALIDADE,
    
    CAST((   CASE WHEN SUM(T1.VL_CONTA) IS NOT NULL THEN SUM(T1.VL_CONTA) ELSE 0 END
            + CASE WHEN SUM(T1.VL_RESSARCIR) IS NOT NULL THEN SUM(T1.VL_RESSARCIR) ELSE 0 END
            + CASE WHEN SUM(T1.VL_REEMBOLSO) IS NOT NULL THEN SUM(T1.VL_REEMBOLSO) ELSE 0 END
            + CASE WHEN SUM(T1.VL_RECURSO) IS NOT NULL THEN SUM(T1.VL_RECURSO) ELSE 0 END
            - CASE WHEN SUM(T1.VL_COPARTICIPACAO) IS NOT NULL THEN SUM(T1.VL_COPARTICIPACAO) ELSE 0 END
    ) / COUNT(DISTINCT CASE WHEN IE_TIPO_SEGURADO IS NOT NULL THEN T1.NR_SEQ_SEGURADO ELSE NULL END) 
     AS DECIMAL(10,2)) AS TICKET_MEDIO_CUSTO,
     
     CAST((CASE WHEN SUM(T1.VL_MENSALIDADE) IS NOT NULL THEN SUM(T1.VL_MENSALIDADE) ELSE 0 END)
     / COUNT(DISTINCT CASE WHEN IE_TIPO_SEGURADO IS NOT NULL THEN T1.NR_SEQ_SEGURADO ELSE NULL END) 
     AS DECIMAL(10,2)) AS TICKET_MEDIO_RECEITA,
     
     CAST((CASE WHEN SUM(T1.VL_MENSALIDADE) IS NOT NULL THEN SUM(T1.VL_MENSALIDADE) ELSE 0 END)
          - ( CASE WHEN SUM(T1.VL_CONTA) IS NOT NULL THEN SUM(T1.VL_CONTA) ELSE 0 END
            + CASE WHEN SUM(T1.VL_RESSARCIR) IS NOT NULL THEN SUM(T1.VL_RESSARCIR) ELSE 0 END
            + CASE WHEN SUM(T1.VL_REEMBOLSO) IS NOT NULL THEN SUM(T1.VL_REEMBOLSO) ELSE 0 END
            + CASE WHEN SUM(T1.VL_RECURSO) IS NOT NULL THEN SUM(T1.VL_RECURSO) ELSE 0 END
            - CASE WHEN SUM(T1.VL_COPARTICIPACAO) IS NOT NULL THEN SUM(T1.VL_COPARTICIPACAO) ELSE 0 END
    ) AS DECIMAL(10,2)) AS RESULTADO,
    
    CASE 
        WHEN SUM(T1.VL_MENSALIDADE) IS NULL THEN 0 -- Se mensalidade for nula
        ELSE
            CAST(
                (
                    CASE WHEN SUM(T1.VL_CONTA) IS NOT NULL THEN SUM(T1.VL_CONTA) ELSE 0 END
                    + CASE WHEN SUM(T1.VL_RESSARCIR) IS NOT NULL THEN SUM(T1.VL_RESSARCIR) ELSE 0 END
                    + CASE WHEN SUM(T1.VL_REEMBOLSO) IS NOT NULL THEN SUM(T1.VL_REEMBOLSO) ELSE 0 END
                    + CASE WHEN SUM(T1.VL_RECURSO) IS NOT NULL THEN SUM(T1.VL_RECURSO) ELSE 0 END
                    - CASE WHEN SUM(T1.VL_COPARTICIPACAO) IS NOT NULL THEN SUM(T1.VL_COPARTICIPACAO) ELSE 0 END
                ) 
                / SUM(T1.VL_MENSALIDADE) AS DECIMAL(10, 5)) END AS RESULTADO_PCT

FROM tasy.PLS_AR_DADOS_V T1

JOIN Tasy.PLS_PLANO T2              ON T2.NR_SEQUENCIA      = T1.NR_SEQ_PLANO

WHERE
    T1.DT_MES_COMPETENCIA >= ADD_MONTHS(TRUNC(SYSDATE, 'YEAR'), - 62) -- Início do período de 5 anos atras
    AND T1.DT_MES_COMPETENCIA < ADD_MONTHS(TRUNC(SYSDATE, 'YEAR'), 12) -- Fim do ano atual
    
GROUP BY
    TO_CHAR(T1.DT_MES_COMPETENCIA, 'YYYY-MM'), 
    T1.NR_SEQ_PLANO, 
    T1.IE_REGULAMENTACAO, 
    T1.IE_TIPO_CONTRATACAO,
    T2.DS_PLANO

ORDER BY
    TO_CHAR(T1.DT_MES_COMPETENCIA, 'YYYY-MM'),
    T1.IE_REGULAMENTACAO,
    T1.IE_TIPO_CONTRATACAO,
    T1.NR_SEQ_PLANO,
    T2.DS_PLANO
