SELECT 
'07/2024' AS COMPETENCIA,
DT_PROTOCOLO,
DT_CONTA_FECHADA,
DT_PAGAMENTO_PREVISTO,
DT_SOLICITACAO,
DT_AUTORIZACAO,
DT_REALIZACAO,
DT_INICIO_FATURAMENTO,
DT_FIM_INTERNACAO,
DT_ATUALIZACAO,
DT_CANCELAMENTO_CONTA,
DT_EXCLUSAO_CONTA,
DT_EVENTO,
DT_PAGAMENTO_RECURSO,
DT_CONTA_FECHADA_RECURSO,
DT_ATUALIZACAO_NREC

FROM Tasy.PLS_MONITOR_TISS_CTA_VAL
WHERE 
NR_SEQ_LOTE_MONITOR = 209