SELECT
TO_CHAR(T2.DT_MES_COMPETENCIA, 'YYYY-MM') AS COMPETENCIA,
T5.CD_PROCEDIMENTO,

--CAST(ROUND(SUM(T5.VL_TOTAL_PROCEDIMENTO) / COUNT(T5.VL_TOTAL_PROCEDIMENTO), 2) AS NUMBER(10, 2)) Medio,
CASE 
    WHEN T1.NR_SEQ_PLANO IN (14, 16, 29, 72)         THEN 'IF_medico'
    WHEN T1.NR_SEQ_PLANO IN (74)                     THEN 'IF_Odonto'
    WHEN T1.NR_SEQ_PLANO IN (3)                      THEN 'CA_Pre'
    WHEN T1.NR_SEQ_PLANO IN (5)                      THEN 'CA_Pre_Odonto'
    WHEN T1.NR_SEQ_PLANO IN (19, 21, 71, 31)         THEN 'CA_Pos'
    WHEN T1.NR_SEQ_PLANO IN (60)                     THEN 'CA_Pos_Odonto'
    WHEN T1.NR_SEQ_PLANO IN (23, 61, 69, 32, 58, 78) THEN 'CE_Pos'
    WHEN T1.NR_SEQ_PLANO IN (73)                     THEN 'CE_Pos_Odonto'
    WHEN T1.NR_SEQ_PLANO IN (42)                     THEN 'Titulo_Associativo'
    WHEN T1.NR_SEQ_PLANO IN (75)                     THEN 'Atendimentos_Particulares'
    WHEN T1.NR_SEQ_PLANO IN (66, 67, 65)             THEN 'Ortodontia'
    WHEN T1.NR_SEQ_PLANO IN (44)                     THEN 'Benef_Compl'
    ELSE 'Verificar'
END AS MODALIDADE,

--SUM(T5.VL_TOTAL_PROCEDIMENTO) TOTAL,
SUM(CASE WHEN T2.NR_SEQ_PRESTADOR = 1661 THEN T5.VL_TOTAL_PROCEDIMENTO ELSE 0 END) AS VAL_SANTA,
SUM(CASE WHEN T2.NR_SEQ_PRESTADOR = 1661 THEN 1 ELSE 0 END) AS COUNT_SANTA,
SUM(CASE WHEN T2.NR_SEQ_PRESTADOR = 2 THEN T5.VL_TOTAL_PROCEDIMENTO ELSE 0 END) AS VAL_ERNESTO,
SUM(CASE WHEN T2.NR_SEQ_PRESTADOR = 2 THEN 1 ELSE 0 END) AS COUNT_ERNESTO,
SUM(CASE WHEN T2.NR_SEQ_PRESTADOR NOT IN (2,1661,1366) THEN T5.VL_TOTAL_PROCEDIMENTO ELSE 0 END) AS VAL_DEMAIS,
COUNT(CASE WHEN T2.NR_SEQ_PRESTADOR NOT IN (2,1661,1366) THEN 1 ELSE 0 END) AS COUNT_DEMAIS,

SUM(CASE WHEN T2.NR_SEQ_PRESTADOR = 1661 THEN T5.VL_TOTAL_PROCEDIMENTO ELSE 0 END)/CASE WHEN SUM(CASE WHEN T2.NR_SEQ_PRESTADOR = 1661 THEN 1 ELSE 0 END) != 0 THEN SUM(CASE WHEN T2.NR_SEQ_PRESTADOR = 1661 THEN 1 ELSE 0 END) ELSE 1 END AS MEDIA_SANTA_CASA,
SUM(CASE WHEN T2.NR_SEQ_PRESTADOR = 2 THEN T5.VL_TOTAL_PROCEDIMENTO ELSE 0 END)/CASE WHEN SUM(CASE WHEN T2.NR_SEQ_PRESTADOR = 2 THEN 1 ELSE 0 END) != 0 THEN SUM(CASE WHEN T2.NR_SEQ_PRESTADOR = 2 THEN 1 ELSE 0 END) ELSE 1 END AS MEDIA_ERNESTO,
SUM(CASE WHEN T2.NR_SEQ_PRESTADOR NOT IN (2,1661,1366) THEN T5.VL_TOTAL_PROCEDIMENTO ELSE 0 END)/CASE WHEN SUM(CASE WHEN T2.NR_SEQ_PRESTADOR NOT IN (2,1661,1366) THEN 1 ELSE 0 END) != 0 THEN SUM(CASE WHEN T2.NR_SEQ_PRESTADOR NOT IN (2,1661,1366) THEN 1 ELSE 0 END) ELSE 1 END  AS MEDIA_OUTROS

--SUM(CASE WHEN T2.NR_SEQ_PRESTADOR NOT IN (2,1661,1366) THEN T5.VL_TOTAL_PROCEDIMENTO ELSE 0 END)/SUM(CASE WHEN T2.NR_SEQ_PRESTADOR NOT IN (2,1661,1366) THEN 1 ELSE 0 END)

--SUM(CASE WHEN T2.NR_SEQ_PRESTADOR = 1661 THEN T5.VL_TOTAL_PROCEDIMENTO ELSE 0 END)/COUNT(CASE WHEN T2.NR_SEQ_PRESTADOR = 1661 THEN T5.VL_TOTAL_PROCEDIMENTO ELSE 1 END)/SUM(CASE WHEN T2.NR_SEQ_PRESTADOR = 2 THEN T5.VL_TOTAL_PROCEDIMENTO ELSE 0 END)/COUNT(CASE WHEN T2.NR_SEQ_PRESTADOR = 2 THEN T5.VL_TOTAL_PROCEDIMENTO ELSE 1 END) - 1  AS VAR

--SUM(T8.VL_LIBERADO) Total_material

--T1.*, T2.*, T3.*, T4.*, T5.*, T6.*, T7.*

FROM Tasy.PLS_CONTA T1

JOIN Tasy.PLS_PROTOCOLO_CONTA T2    ON T2.NR_SEQUENCIA      = T1.NR_SEQ_PROTOCOLO
JOIN Tasy.PLS_PLANO T3              ON T3.NR_SEQUENCIA      = T1.NR_SEQ_PLANO
JOIN Tasy.PLS_PRESTADOR T4          ON T4.NR_SEQUENCIA      = T2.NR_SEQ_PRESTADOR
JOIN Tasy.PESSOA_JURIDICA T9        ON T9.CD_CGC            = T4.CD_CGC
--ta repetido os procedimentos
RIGHT JOIN Tasy.PLS_CONTA_PROC T5         ON T5.NR_SEQ_CONTA      = T1.NR_SEQUENCIA
--RIGHT JOIN Tasy.pls_conta_mat T8          ON T8.NR_SEQ_CONTA      = T1.NR_SEQUENCIA
--JOIN Tasy.PROCEDIMENTO T6           ON T6.CD_PROCEDIMENTO   = T5.CD_PROCEDIMENTO
--LEFT JOIN Tasy.ctb_balancete_v T7   ON T7.CD_CONTA_CONTABIL = T5.CD_CONTA_DEB
--LEFT JOIN Tasy.CONTA_CONTABIL T8 ON T8.CD_CONTA_CONTABIL = T5.CD_CONTA_DEB

WHERE
(T2.DT_MES_COMPETENCIA  >= TRUNC(SYSDATE, 'YEAR') AND T2.DT_MES_COMPETENCIA < ADD_MONTHS(TRUNC(SYSDATE, 'YEAR'), 12))
--AND (Tasy.CTB_OBTER_SE_MES_FECHADO(T7.NR_SEQ_MES_REF, 2) = 'F')
--AND T2.DT_MES_COMPETENCIA = TO_DATE('01-01-2024', 'DD-MM-YYYY')
--AND T2.DT_MES_COMPETENCIA < TO_DATE('01-09-2024', 'DD-MM-YYYY')
--AND T3.NR_SEQUENCIA IN (44, 3, 42)
--AND T5.CD_CONTA_DEB IS NOT NULL
--AND T5.IE_STATUS IN ('4', '3', '6')
AND T1.ie_status IN ('F')
--AND T5.CD_CONTA_PROVISAO_DEB IS NOT NULL
--AND T5.CD_CONTA_DEB IS NULL
--AND T2.NR_SEQ_PRESTADOR IN (1661, 2)
--AND T5.VL_TOTAL_PROCEDIMENTO != 0

GROUP BY
TO_CHAR(T2.DT_MES_COMPETENCIA, 'YYYY-MM'),
T5.CD_PROCEDIMENTO,
CASE 
    WHEN T1.NR_SEQ_PLANO IN (14, 16, 29, 72)         THEN 'IF_medico'
    WHEN T1.NR_SEQ_PLANO IN (74)                     THEN 'IF_Odonto'
    WHEN T1.NR_SEQ_PLANO IN (3)                      THEN 'CA_Pre'
    WHEN T1.NR_SEQ_PLANO IN (5)                      THEN 'CA_Pre_Odonto'
    WHEN T1.NR_SEQ_PLANO IN (19, 21, 71, 31)         THEN 'CA_Pos'
    WHEN T1.NR_SEQ_PLANO IN (60)                     THEN 'CA_Pos_Odonto'
    WHEN T1.NR_SEQ_PLANO IN (23, 61, 69, 32, 58, 78) THEN 'CE_Pos'
    WHEN T1.NR_SEQ_PLANO IN (73)                     THEN 'CE_Pos_Odonto'
    WHEN T1.NR_SEQ_PLANO IN (42)                     THEN 'Titulo_Associativo'
    WHEN T1.NR_SEQ_PLANO IN (75)                     THEN 'Atendimentos_Particulares'
    WHEN T1.NR_SEQ_PLANO IN (66, 67, 65)             THEN 'Ortodontia'
    WHEN T1.NR_SEQ_PLANO IN (44)                     THEN 'Benef_Compl'
    ELSE 'Verificar'
END

ORDER BY
TO_CHAR(T2.DT_MES_COMPETENCIA, 'YYYY-MM') ASC,
T5.CD_PROCEDIMENTO ASC,
CASE 
    WHEN T1.NR_SEQ_PLANO IN (14, 16, 29, 72)         THEN 'IF_medico'
    WHEN T1.NR_SEQ_PLANO IN (74)                     THEN 'IF_Odonto'
    WHEN T1.NR_SEQ_PLANO IN (3)                      THEN 'CA_Pre'
    WHEN T1.NR_SEQ_PLANO IN (5)                      THEN 'CA_Pre_Odonto'
    WHEN T1.NR_SEQ_PLANO IN (19, 21, 71, 31)         THEN 'CA_Pos'
    WHEN T1.NR_SEQ_PLANO IN (60)                     THEN 'CA_Pos_Odonto'
    WHEN T1.NR_SEQ_PLANO IN (23, 61, 69, 32, 58, 78) THEN 'CE_Pos'
    WHEN T1.NR_SEQ_PLANO IN (73)                     THEN 'CE_Pos_Odonto'
    WHEN T1.NR_SEQ_PLANO IN (42)                     THEN 'Titulo_Associativo'
    WHEN T1.NR_SEQ_PLANO IN (75)                     THEN 'Atendimentos_Particulares'
    WHEN T1.NR_SEQ_PLANO IN (66, 67, 65)             THEN 'Ortodontia'
    WHEN T1.NR_SEQ_PLANO IN (44)                     THEN 'Benef_Compl'
    ELSE 'Verificar'
END ASC

