SELECT 
T2.DT_MES_COMPETENCIA,
T5.CD_PROCEDIMENTO,
T6.DS_PROCEDIMENTO,
T6.DS_COMPLEMENTO,
T6.CD_TIPO_PROCEDIMENTO,
CD_TIPO_TABELA,
T2.NR_SEQ_PRESTADOR,
T2.NR_CPF_PRESTADOR_IMP,
T1.NR_SEQ_CBO_SAUDE,
T1.NR_SEQ_CBO_SAUDE_SOLIC,
T1.CD_MEDICO_EXECUTOR,
T1.CD_MEDICO_EXECUTOR_IMP,
T1.CD_MEDICO_SOLICITANTE,
T1.CD_MEDICO_SOLICITANTE_IMP,
T1.CD_PRESTADOR_EXEC_IMP,
T1.CD_PRESTADOR_SOLIC_IMP,
T2.CD_CGC_PRESTADOR_IMP,

T1.*, T2.*, T3.*, T4.*

FROM Tasy.PLS_CONTA T1

LEFT JOIN Tasy.PLS_PROTOCOLO_CONTA T2 ON T1.NR_SEQ_PROTOCOLO = T2.NR_SEQUENCIA
LEFT JOIN Tasy.PLS_PLANO T3 ON T1.NR_SEQ_PLANO = T3.NR_SEQUENCIA
LEFT JOIN Tasy.PLS_PRESTADOR T4 ON T4.NR_SEQUENCIA = T2.NR_SEQ_PRESTADOR
JOIN Tasy.PLS_CONTA_PROC T5 ON T5.NR_SEQ_CONTA = T1.NR_SEQUENCIA
LEFT JOIN Tasy.PROCEDIMENTO T6 ON T6.CD_PROCEDIMENTO = T5.CD_PROCEDIMENTO

WHERE
(T2.DT_MES_COMPETENCIA  >= TRUNC(SYSDATE, 'YEAR') AND T2.DT_MES_COMPETENCIA < ADD_MONTHS(TRUNC(SYSDATE, 'YEAR'), 12))
AND T1.NR_SEQ_PRESTADOR = 1366
--AND T1.NR_SEQUENCIA = 7645953
AND T1.NR_SEQ_CBO_SAUDE IS NULL
AND T1.NR_SEQ_CBO_SAUDE_SOLIC IS NULL
AND T1.CD_MEDICO_EXECUTOR IS NULL
AND T1.CD_MEDICO_EXECUTOR_IMP IS NULL
AND T1.CD_MEDICO_SOLICITANTE IS NULL
AND T1.CD_MEDICO_SOLICITANTE_IMP IS NULL
AND T1.CD_PRESTADOR_EXEC_IMP IS NULL
AND T2.NR_SEQ_MOTIVO_CANCEL IS NULL
AND T2.CD_CGC_PRESTADOR_IMP IS NULL
AND T2.NR_CPF_PRESTADOR_IMP IS NULL

ORDER BY 1 DESC
