SELECT
TO_CHAR(T2.DT_MES_COMPETENCIA, 'YYYY-MM') Competencia,
T8.CD_CONTA_DEB,
T3.NR_SEQUENCIA PLANO,
SUM(T8.VL_LIBERADO) VL_LIBERADO,
SUM(T8.VL_GLOSA) VL_GLOSA,
SUM(T8.VL_PARTICIPACAO) VL_PARTICIPACAO
--T1.NR_SEQ_PROTOCOLO,
--T1.NR_SEQ_PLANO,
--T2.NR_SEQ_PRESTADOR,
--T5.NR_SEQ_CONTA,
--T5.CD_PROCEDIMENTO

--T1.*, T2.*, T3.*, T4.*, T5.*, T6.*, T7.*

FROM Tasy.PLS_CONTA T1

JOIN Tasy.PLS_PROTOCOLO_CONTA T2    ON T2.NR_SEQUENCIA      = T1.NR_SEQ_PROTOCOLO
JOIN Tasy.PLS_PLANO T3              ON T3.NR_SEQUENCIA      = T1.NR_SEQ_PLANO
JOIN Tasy.PLS_PRESTADOR T4          ON T4.NR_SEQUENCIA      = T2.NR_SEQ_PRESTADOR
--JOIN Tasy.PLS_CONTA_PROC T5         ON T5.NR_SEQ_CONTA      = T1.NR_SEQUENCIA
JOIN Tasy.pls_conta_mat T8          ON T8.NR_SEQ_CONTA      = T1.NR_SEQUENCIA
--JOIN Tasy.PROCEDIMENTO T6           ON T6.CD_PROCEDIMENTO   = T5.CD_PROCEDIMENTO
LEFT JOIN Tasy.CONTA_CONTABIL T9 ON T9.CD_CONTA_CONTABIL = T8.CD_CONTA_DEB
--LEFT JOIN Tasy.ctb_balancete_v T7   ON (T7.CD_CONTA_CONTABIL = T8.CD_CONTA_CONTABIL AND TO_CHAR(T2.DT_MES_COMPETENCIA, 'YYYY-MM') = TO_CHAR(T7.DT_REFERENCIA, 'YYYY-MM'))

WHERE
(T2.DT_MES_COMPETENCIA  >= TRUNC(SYSDATE, 'YEAR') AND T2.DT_MES_COMPETENCIA < ADD_MONTHS(TRUNC(SYSDATE, 'YEAR'), 12))
--AND (Tasy.CTB_OBTER_SE_MES_FECHADO(T7.NR_SEQ_MES_REF, 2) = 'F')
--AND T2.DT_MES_COMPETENCIA = TO_DATE('01-01-2024', 'DD-MM-YYYY')
AND T2.DT_MES_COMPETENCIA < TO_DATE('01-09-2024', 'DD-MM-YYYY')
AND T3.NR_SEQUENCIA IN (44, 3, 42)
--AND T5.CD_CONTA_DEB IS NOT NULL
AND T2.IE_STATUS IN ('4', '3', '6')
AND T1.ie_status IN ('F')
--AND T5.CD_CONTA_PROVISAO_DEB IS NOT NULL
--AND T5.CD_CONTA_DEB IS NULL

GROUP BY
TO_CHAR(T2.DT_MES_COMPETENCIA, 'YYYY-MM'),
T8.CD_CONTA_DEB,
T3.NR_SEQUENCIA

ORDER BY 1 ASC
