SELECT
TO_CHAR(T1.DT_MESANO_REFERENCIA, 'MM/YYYY') Competencia,
T1.NR_SEQ_PLANO,
T1.NR_SEQ_SEGURADO,
T1.NR_SEQ_CONTRATO,
SUM(T1.VL_MENSALIDADE) Mensalidade

FROM Tasy.PLS_MENSALIDADE_SEGURADO T1
WHERE 
T1.DT_MESANO_REFERENCIA >= TRUNC(SYSDATE, 'YEAR') AND T1.DT_MESANO_REFERENCIA < ADD_MONTHS(TRUNC(SYSDATE, 'YEAR'), 12)

GROUP BY 
TO_CHAR(T1.DT_MESANO_REFERENCIA, 'MM/YYYY'),
T1.NR_SEQ_PLANO,
T1.NR_SEQ_SEGURADO,
T1.NR_SEQ_CONTRATO

ORDER BY Competencia,
T1.NR_SEQ_PLANO,
T1.NR_SEQ_CONTRATO,
T1.NR_SEQ_SEGURADO

