SELECT
    T1.DT_REFERENCIA competencia,
    
    ((SUM(CASE WHEN T1.CD_CLASSIF_SEM_PONTO = 41 THEN T1.VL_SALDO ELSE 0 END) 
    - SUM(CASE WHEN T1.CD_CLASSIF_SEM_PONTO = 415 THEN T1.VL_SALDO ELSE 0 END)
    - SUM(CASE WHEN T1.CD_CLASSIF_SEM_PONTO = 416 THEN T1.VL_SALDO ELSE 0 END)
   ) / SUM(CASE WHEN T1.CD_CLASSIF_SEM_PONTO = 31 THEN T1.VL_SALDO ELSE 1 END)) AS Sinistralidade,

    (SUM(CASE WHEN T1.CD_CLASSIF_SEM_PONTO = 41 THEN T1.VL_DEBITO - T1.VL_CREDITO ELSE 0 END))  AS EIL,
    (SUM(CASE WHEN T1.CD_CLASSIF_SEM_PONTO = 43 THEN T1.VL_DEBITO - T1.VL_CREDITO ELSE 0 END))  AS DC,
    (SUM(CASE WHEN T1.CD_CLASSIF_SEM_PONTO = 46 THEN T1.VL_DEBITO - T1.VL_CREDITO ELSE 0 END))  AS DA,
    (SUM(CASE WHEN T1.CD_CLASSIF_SEM_PONTO = 466 THEN T1.VL_DEBITO - T1.VL_CREDITO ELSE 0 END)) AS MultasAdm,
    (SUM(CASE WHEN T1.CD_CLASSIF_SEM_PONTO = 31 THEN T1.VL_CREDITO - T1.VL_DEBITO ELSE 0 END))  AS contraprestacoes,
    (SUM(CASE WHEN T1.CD_CLASSIF_SEM_PONTO = 312 THEN T1.VL_CREDITO - T1.VL_DEBITO ELSE 0 END))  AS var_pic,
    ((SUM(CASE WHEN T1.CD_CLASSIF_SEM_PONTO = 31 THEN T1.VL_CREDITO - T1.VL_DEBITO ELSE 0 END)) 
    -(SUM(CASE WHEN T1.CD_CLASSIF_SEM_PONTO = 312 THEN T1.VL_CREDITO - T1.VL_DEBITO ELSE 0 END))) AS contraprestacoes_liquidas,
    (SUM(CASE WHEN T1.CD_CLASSIF_SEM_PONTO = 31111 THEN T1.VL_CREDITO - T1.VL_DEBITO ELSE 0 END))  AS contraprestacoes_medico_hosp,
    (SUM(CASE WHEN T1.CD_CLASSIF_SEM_PONTO = 21111101301 THEN T1.VL_SALDO ELSE 0 END))  AS PIC_contabil

FROM    Tasy.ctb_balancete_v T1

WHERE 
    ((T1.IE_NORMAL_ENCERRAMENTO = 'N' AND EXTRACT(MONTH FROM T1.DT_REFERENCIA) != 12)
    OR (EXTRACT(MONTH FROM T1.DT_REFERENCIA) = 12 AND T1.IE_NORMAL_ENCERRAMENTO = 'E')) 
    AND T1.DT_REFERENCIA BETWEEN 
        ADD_MONTHS(TRUNC(SYSDATE, 'MM'), - 85) + 1
        AND 
        TRUNC(SYSDATE, 'MM') - 1
    AND T1.CD_ESTABELECIMENTO = 2
    AND Tasy.CTB_OBTER_SE_MES_FECHADO(T1.NR_SEQ_MES_REF, 2) = 'F'
        
GROUP BY T1.DT_REFERENCIA
ORDER BY T1.DT_REFERENCIA ASC
