SELECT
TO_CHAR(T1.DT_MESANO_REFERENCIA, 'MM/YYYY') Competencia,

SUM(CASE WHEN T1.NR_SEQ_PLANO IN (14, 16, 29, 72) THEN T1.VL_MENSALIDADE END) AS IF,
SUM(CASE WHEN T1.NR_SEQ_PLANO IN (74) THEN T1.VL_MENSALIDADE END) AS IF_Odonto,

SUM(CASE WHEN T1.NR_SEQ_PLANO IN (3) THEN T1.VL_MENSALIDADE END) AS CA_Pre,
SUM(CASE WHEN T1.NR_SEQ_PLANO IN (5) THEN T1.VL_MENSALIDADE END) AS CA_Pre_Odonto,

SUM(CASE WHEN T1.NR_SEQ_PLANO IN (19, 21, 71, 31) THEN T1.VL_MENSALIDADE END) AS CA_Pos,
SUM(CASE WHEN T1.NR_SEQ_PLANO IN (60) THEN T1.VL_MENSALIDADE END) AS CA_Pos_Odonto,

SUM(CASE WHEN T1.NR_SEQ_PLANO IN (23, 61, 69, 32, 58, 78) THEN T1.VL_MENSALIDADE END) AS CE_Pos,
SUM(CASE WHEN T1.NR_SEQ_PLANO IN (73) THEN T1.VL_MENSALIDADE END) AS CE_Pos_Odonto,

SUM(CASE WHEN T1.NR_SEQ_PLANO IN (42) THEN T1.VL_MENSALIDADE END) AS Titulo_Associativo,
SUM(CASE WHEN T1.NR_SEQ_PLANO IN (75) THEN T1.VL_MENSALIDADE END) AS Atendimentos_Particulares,
SUM(CASE WHEN T1.NR_SEQ_PLANO IN (66, 67, 65) THEN T1.VL_MENSALIDADE END) AS Ortodontia,
SUM(CASE WHEN T1.NR_SEQ_PLANO IN (44) THEN T1.VL_MENSALIDADE END) AS Benef_Compl,

SUM(T1.VL_MENSALIDADE) Mensalidade

FROM Tasy.PLS_MENSALIDADE_SEGURADO T1
WHERE 
T1.DT_MESANO_REFERENCIA >= TRUNC(SYSDATE, 'YEAR') AND T1.DT_MESANO_REFERENCIA < ADD_MONTHS(TRUNC(SYSDATE, 'YEAR'), 12)

GROUP BY 
TO_CHAR(T1.DT_MESANO_REFERENCIA, 'MM/YYYY')

ORDER BY Competencia