SELECT DISTINCT
TO_CHAR(T1.DT_MOVIMENTO, 'YYYY-MM') AS COMPETENCIA,
T1.NR_SEQUENCIA,
T1.NR_SEQ_MOVTO_PARTIDA,
T5.NR_SEQUENCIA,
T1.VL_MOVIMENTO,

T1.CD_HISTORICO,
T5.CD_HISTORICO,
T2.DS_HISTORICO,
T1.DS_COMPL_HISTORICO,
T5.DS_COMPL_HISTORICO,

T1.NR_LOTE_CONTABIL,
T5.NR_LOTE_CONTABIL,

T1.DT_MOVIMENTO,
T5.DT_MOVIMENTO,

T1.CD_CONTA_DEBITO,
T5.CD_CONTA_DEBITO,
T1.CD_CONTA_CREDITO,
T5.CD_CONTA_CREDITO,


T1.NR_SEQ_AGRUPAMENTO,
T5.NR_SEQ_AGRUPAMENTO,

T1.CD_CLASSIF_DEBITO,
T5.CD_CLASSIF_DEBITO,

T1.CD_CLASSIF_CREDITO,
T5.CD_CLASSIF_CREDITO,

T1.NR_DOCUMENTO,
T5.NR_DOCUMENTO,

T1.NR_AGRUP_SEQUENCIAL,
T1.IE_ORIGEM_DOCUMENTO,
T1.IE_STATUS_ORIGEM,
T1.DT_ATUALIZACAO_SALDO,
T1.NM_USUARIO,
T5.NM_USUARIO,

T6.*
--T1.DS_COMPL_HISTORICO,
--COUNT(*) AS QNT,
--SUM(CASE WHEN CD_CONTA_DEBITO = 44065 THEN VL_MOVIMENTO ELSE 0 END) - SUM(CASE WHEN CD_CONTA_CREDITO = 44065 THEN (VL_MOVIMENTO) ELSE 0 END) AS D44,
--SUM(CASE WHEN CD_CONTA_DEBITO = 44064 THEN VL_MOVIMENTO ELSE 0 END) - SUM(CASE WHEN CD_CONTA_CREDITO = 44064 THEN (VL_MOVIMENTO) ELSE 0 END) AS Titulo_associativo,
--SUM(CASE WHEN CD_CONTA_DEBITO IN (40019) THEN VL_MOVIMENTO ELSE 0 END) - SUM(CASE WHEN CD_CONTA_CREDITO IN (40019) THEN (VL_MOVIMENTO) ELSE 0 END) AS CA_medico,
--SUM(CASE WHEN CD_CONTA_DEBITO IN (40072) THEN VL_MOVIMENTO ELSE 0 END) - SUM(CASE WHEN CD_CONTA_CREDITO IN (40072) THEN (VL_MOVIMENTO) ELSE 0 END) AS CA_odonto,
--SUM(CASE WHEN CD_CONTA_DEBITO IN (40019, 40072) THEN VL_MOVIMENTO ELSE 0 END) - SUM(CASE WHEN CD_CONTA_CREDITO IN (40019, 40072) THEN (VL_MOVIMENTO) ELSE 0 END) AS CA


FROM tasy.CTB_MOVIMENTO T1

JOIN Tasy.HISTORICO_PADRAO T2 ON T1.CD_HISTORICO = T2.CD_HISTORICO
--JOIN tasy.CTB_CLASSIF_MOVIMENTO T3 ON T1.NR_SEQ_CLASSIF_MOVTO = T3.NR_SEQUENCIA
JOIN tasy.CTB_MES_REF T4 ON T1.NR_SEQ_MES_REF = T4.NR_SEQUENCIA
LEFT JOIN tasy.CTB_MOVIMENTO T5 ON T1.NR_SEQ_MOVTO_PARTIDA = T5.NR_SEQUENCIA
LEFT JOIN tasy.LOTE_CONTABIL T6 ON T1.NR_LOTE_CONTABIL = T6.NR_LOTE_CONTABIL

WHERE
(T1.CD_CONTA_DEBITO IN (44065, 44064, 40019, 40072) OR T1.CD_CONTA_CREDITO IN (44065, 44064, 40019, 40072))
AND T1.DT_MOVIMENTO >= TO_DATE('01-01-2024', 'DD-MM-YYYY')
--AND NR_SEQ_MES_REF >= 1565
AND T1.CD_HISTORICO NOT IN (232, 1083, 1089)
AND T4.DT_BLOQUEIO IS NOT NULL


--GROUP BY 
--TO_CHAR(DT_MOVIMENTO, 'YYYY-MM'),
--T1.CD_HISTORICO,
--T2.DS_HISTORICO
--,T1.DS_COMPL_HISTORICO

ORDER BY 

--,COUNT(*) DESC
--T1.NR_SEQUENCIA ASC
T1.VL_MOVIMENTO DESC,
TO_CHAR(T1.DT_MOVIMENTO, 'YYYY-MM')
