SELECT
TO_CHAR(T2.DT_MES_COMPETENCIA, 'YYYY-MM') AS COMPETENCIA,
--T5.CD_CONTA_DEB,
--T1.IE_STATUS,
--T2.NR_SEQ_PRESTADOR,
T5.CD_PROCEDIMENTO,
SUM(T5.VL_TOTAL_PROCEDIMENTO) TOTAL,
COUNT(T5.VL_TOTAL_PROCEDIMENTO) QNT,
CAST(ROUND(SUM(T5.VL_TOTAL_PROCEDIMENTO) / COUNT(T5.VL_TOTAL_PROCEDIMENTO), 2) AS NUMBER(10, 2)) Medio,
CASE 
    WHEN T1.NR_SEQ_PLANO IN (14, 16, 29, 72)         THEN 'IF_medico'
    WHEN T1.NR_SEQ_PLANO IN (74)                     THEN 'IF_Odonto'
    WHEN T1.NR_SEQ_PLANO IN (3)                      THEN 'CA_Pre'
    WHEN T1.NR_SEQ_PLANO IN (5)                      THEN 'CA_Pre_Odonto'
    WHEN T1.NR_SEQ_PLANO IN (19, 21, 71, 31)         THEN 'CA_Pos'
    WHEN T1.NR_SEQ_PLANO IN (60)                     THEN 'CA_Pos_Odonto'
    WHEN T1.NR_SEQ_PLANO IN (23, 61, 69, 32, 58, 78) THEN 'CE_Pos'
    WHEN T1.NR_SEQ_PLANO IN (73)                     THEN 'CE_Pos_Odonto'
    WHEN T1.NR_SEQ_PLANO IN (42)                     THEN 'Titulo_Associativo'
    WHEN T1.NR_SEQ_PLANO IN (75)                     THEN 'Atendimentos_Particulares'
    WHEN T1.NR_SEQ_PLANO IN (66, 67, 65)             THEN 'Ortodontia'
    WHEN T1.NR_SEQ_PLANO IN (44)                     THEN 'Benef_Compl'
    ELSE 'Verificar'
END AS MODALIDADE

--SUM(T8.VL_LIBERADO) Total_material,
--COUNT(T8.VL_LIBERADO)

--T1.*, T2.*, T3.*, T4.*, T5.*, T6.*, T7.*

FROM Tasy.PLS_CONTA T1

JOIN Tasy.PLS_PROTOCOLO_CONTA T2    ON T2.NR_SEQUENCIA      = T1.NR_SEQ_PROTOCOLO
JOIN Tasy.PLS_PLANO T3              ON T3.NR_SEQUENCIA      = T1.NR_SEQ_PLANO
--JOIN Tasy.PLS_PRESTADOR T4          ON T4.NR_SEQUENCIA      = T2.NR_SEQ_PRESTADOR
RIGHT JOIN Tasy.PLS_CONTA_PROC T5   ON T5.NR_SEQ_CONTA      = T1.NR_SEQUENCIA
--RIGHT JOIN Tasy.pls_conta_mat T8          ON T8.NR_SEQ_CONTA      = T1.NR_SEQUENCIA
--JOIN Tasy.PROCEDIMENTO T6           ON T6.CD_PROCEDIMENTO   = T5.CD_PROCEDIMENTO
--LEFT JOIN Tasy.ctb_balancete_v T7   ON T7.CD_CONTA_CONTABIL = T5.CD_CONTA_DEB
--LEFT JOIN Tasy.CONTA_CONTABIL T8 ON T8.CD_CONTA_CONTABIL = T5.CD_CONTA_DEB

WHERE
(T2.DT_MES_COMPETENCIA  >= TRUNC(SYSDATE, 'YEAR') AND T2.DT_MES_COMPETENCIA < ADD_MONTHS(TRUNC(SYSDATE, 'YEAR'), 12))
--AND (Tasy.CTB_OBTER_SE_MES_FECHADO(T7.NR_SEQ_MES_REF, 2) = 'F')
--AND T2.DT_MES_COMPETENCIA = TO_DATE('01-01-2024', 'DD-MM-YYYY')
-- T2.DT_MES_COMPETENCIA < TO_DATE('01-09-2024', 'DD-MM-YYYY')
--AND T3.NR_SEQUENCIA IN (44, 3, 42)
--AND T5.CD_CONTA_DEB IS NOT NULL
--AND T5.IE_STATUS IN ('4', '3', '6')
--AND T1.ie_status IN ()
--AND (T5.CD_CONTA_PROVISAO_DEB IN ('44751', '40019', '44752', '44753', '44754', '40072', '44755', '44756', '44064', '44065', '44076', '46151')  
--OR   T5.CD_CONTA_DEB IN ('44751', '40019', '44752', '44753', '44754', '40072', '44755', '44756', '44064', '44065', '44076', '46151'))
AND T2.NR_SEQ_PRESTADOR IN ('1366')

GROUP BY
T2.DT_MES_COMPETENCIA,
--T5.CD_CONTA_DEB,
--T1.IE_STATUS,
--T2.NR_SEQ_PRESTADOR,
T5.CD_PROCEDIMENTO,
CASE 
    WHEN T1.NR_SEQ_PLANO IN (14, 16, 29, 72)         THEN 'IF_medico'
    WHEN T1.NR_SEQ_PLANO IN (74)                     THEN 'IF_Odonto'
    WHEN T1.NR_SEQ_PLANO IN (3)                      THEN 'CA_Pre'
    WHEN T1.NR_SEQ_PLANO IN (5)                      THEN 'CA_Pre_Odonto'
    WHEN T1.NR_SEQ_PLANO IN (19, 21, 71, 31)         THEN 'CA_Pos'
    WHEN T1.NR_SEQ_PLANO IN (60)                     THEN 'CA_Pos_Odonto'
    WHEN T1.NR_SEQ_PLANO IN (23, 61, 69, 32, 58, 78) THEN 'CE_Pos'
    WHEN T1.NR_SEQ_PLANO IN (73)                     THEN 'CE_Pos_Odonto'
    WHEN T1.NR_SEQ_PLANO IN (42)                     THEN 'Titulo_Associativo'
    WHEN T1.NR_SEQ_PLANO IN (75)                     THEN 'Atendimentos_Particulares'
    WHEN T1.NR_SEQ_PLANO IN (66, 67, 65)             THEN 'Ortodontia'
    WHEN T1.NR_SEQ_PLANO IN (44)                     THEN 'Benef_Compl'
    ELSE 'Verificar'
END

ORDER BY
T2.DT_MES_COMPETENCIA ASC,
SUM(T5.VL_TOTAL_PROCEDIMENTO) / COUNT(T5.VL_TOTAL_PROCEDIMENTO) DESC